version: "3.8"

services:
  test_runner:
    image: eth2-tax:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: [
        "pytest",
    ]
    environment:
      DB_URI:
      REDIS_HOST: ${REDIS_HOST:-redis_test}
      REDIS_PORT: ${REDIS_PORT:-6379}
      BEACON_NODE_HOST: ${BEACON_NODE_HOST:-localhost}
      BEACON_NODE_PORT: ${BEACON_NODE_PORT:-5052}
      BEACON_NODE_RESPONSE_TIMEOUT: ${BEACON_NODE_RESPONSE_TIMEOUT:-30}
      EXECUTION_NODE_HOST: ${EXECUTION_NODE_HOST:-localhost}
      EXECUTION_NODE_PORT: ${EXECUTION_NODE_PORT:-8545}
      EXECUTION_NODE_RESPONSE_TIMEOUT: ${EXECUTION_NODE_RESPONSE_TIMEOUT:-10}
      EXECUTION_NODE_INFURA_ARCHIVE_URL: ${EXECUTION_NODE_INFURA_ARCHIVE_URL:-}
    volumes:
      - ./tests:/app/tests
    depends_on:
      - db_test
      - redis_test

  db_test:
    image: postgres:13.9
    restart: unless-stopped
    environment:
      POSTGRES_USER: db_test_username
      POSTGRES_PASSWORD: db_test_password
      POSTGRES_DB: db_test

  redis_test:
    image: redis:7.0.8
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ${ABSOLUTE_ROOT_PATH}/etc/redis.conf:/usr/local/etc/redis/redis.conf
